### PR TITLE
Add linux/386 to default platforms

### PR DESCRIPTION
**Pull request by anmaxvl**
This enables cri discover and pull images with 32-bit arch

Signed-off-by: Maksim An <maksiman@microsoft.com>

### CODE REVIEW

**Comment by anmaxvl** [comment]
fyi @katiewasnothere @kevpar @ambarve @dcantah

**Comment by anmaxvl** [comment]
The change can be tested with [this docker image](https://hub.docker.com/layers/129255001/anmaxvl/multiarch-example/buildx-latest/images/sha256-cd93bd159fae734923a77e28b5f6aea25cd40eba43b70415d54aa16b95b4e4ad?context=explore).

**Comment by katiewasnothere** [comment]
Just curious, did you also run the full cri-containerd test suite?

**Comment by anmaxvl** [comment]
> Just curious, did you also run the full cri-containerd test suite?

yeah. I saw some failures, but I don't think they were related to this change.

**Comment by dcantah** [comment]
@anmaxvl Did the new kernel work out fine with 32 bit images?

**Comment by anmaxvl** [comment]
> @anmaxvl Did the new kernel work out fine with 32 bit images?

yep yep

**Review by katiewasnothere — APPROVED** [review]
LGTM

**Review by dcantah — APPROVED** [review]
LGTM

**Pull request merged**
