### PR TITLE
Do not cache image handler.

### PR DESCRIPTION
**Pull request by dcantah**
Signed-off-by: Lantao Liu <lantaol@google.com>

### CODE REVIEW

**Comment by dcantah** [comment]
Cherry-pick to fix image GC issue described below. @katiewasnothere @kevpar 

The issue we were seeing is when importing local images and then pulling the same image:tag and trying to run a container with this, if the image had a new version this would fail with 'error unpacking image: content digest sha256:1234...: not found'. As the image ID entry in the containerd store isn't updated with this process, and the CRI plugin was keeping a reference to the containerd image object, when doing a local resolve using the image ID it would use the old image object to try and run the container. The fix is to ask for a new containerd image object every time during container creation instead of the cached value as it might not be up to date. 

Here's a nice overview of a similar workflow. https://github.com/containerd/containerd/issues/3401

**Comment by kevpar** [comment]
Can you add a description of the problem we observed, and what the underlying cause was?

**Comment by dcantah** [comment]
Yep for sure.

**Comment by dcantah** [comment]
@kevpar done

**Review by kevpar — APPROVED** [review]
LGTM

**Pull request merged**
