### PR TITLE
Re-vendor dependencies

### PR DESCRIPTION
**Pull request by kevpar**
- Pulls in a new version of github.com/containerd/ttrpc from a fork
  to fix the deadlock issue in containerd/ttrpc#72. Will revert back to
  the upstream ttrpc vendor once the fix is merged (containerd/ttrpc#73).
- Pulls in github.com/kevpar/containerd for the ETW stack dump fix as well.
- Includes some vendoring cleanup from running "vndr".

Signed-off-by: Kevin Parsons <kevpar@microsoft.com>

### CODE REVIEW

**Comment by kevpar** [comment]
@ambarve @anmaxvl @dcantah @katiewasnothere PTAL

**Review by anmaxvl — APPROVED** [review]
LGTM. I assume that extra changes being vendored in are OK?

**Comment by kevpar** [comment]
> LGTM. I assume that extra changes being vendored in are OK?

Yes, that's just some vendor cleanup that was performed automatically.

**Comment by dcantah** [comment]
Are we supposed to focus our reviewing efforts of the deadlock ttrpc changes here or the upstream PR? I take it this is a "this fixes the issue and barring any critical flaws we saw, just want a set of eyes on the vendored files", am I off?

**Comment by kevpar** [comment]
> Are we supposed to focus our reviewing efforts of the deadlock ttrpc changes here or the upstream PR? I take it this is a "this fixes the issue and barring any critical flaws we saw, just want a set of eyes on the vendored files", am I off?

Mostly need focus on the upstream ttrpc PR. Comments here would be good if there are any concerns unique to this PR, such as from the vendoring or other ttrpc changes being brought in.

**Review by dcantah — APPROVED** [review]
@kevpar Gotcha. LGTM then vendor wise

**Comment by kevpar** [comment]
Re-purposing this to be a general revendor PR and pulling in one more change. Will need another look in a moment.

**Review by dcantah — APPROVED** [review]
LGTM

**Pull request merged**
