### PR TITLE
Revendor hcsshim to c7c44e13fdacc83a07931653b47a21579f39063c

### PR DESCRIPTION
**Pull request by ambarve**
Signed-off-by: Amit Barve <ambarve@microsoft.com>

### CODE REVIEW

**Comment by kevpar** [comment]
Worth noting that we are moving from vendoring a tagged release to just a commit off of `master`. I think this is fine because we control the full release process and can make whatever fixes in hcsshim we need if needed.

**Review by kevpar — APPROVED** [review]
LGTM

**Review by dcantah — APPROVED** [review]

**Comment by dcantah** [comment]
Thanks Amit

**Comment by ambarve** [comment]
@kevpar could you also please merge this? Thanks.

**Pull request merged**
