### PR TITLE
LCOW: Remove /run mount from default container spec

### PR DESCRIPTION
**Pull request by kevpar**
The default container spec from containerd includes a tmpfs mount on
/run. However, some container images rely on having specific content in
/run, so we don't want to override it. This also matches the upstream
CRI behavior, which also removes the default /run mount.

Signed-off-by: Kevin Parsons <kevpar@microsoft.com>

### CODE REVIEW

**Comment by kevpar** [comment]
@anmaxvl @ambarve @dcantah @katiewasnothere PTAL

**Review by anmaxvl — APPROVED** [review]
lgtm. if anyone else needs a reference https://github.com/jterry75/cri/blob/windows_port/pkg/server/container_create_unix.go#L698-L729

**Review by katiewasnothere — COMMENTED** [review]
LGTM

**Review by katiewasnothere — APPROVED** [review]
clicked the wrong option, LGTM 😅

**Pull request merged**
