### PR TITLE
Prevent potential nil reference panics when querying for windows container stats

### PR DESCRIPTION
**Pull request by katiewasnothere**
Signed-off-by: Kathryn Baldauf <kabaldau@microsoft.com>

### CODE REVIEW

**Comment by dcantah** [comment]
More checks are always good and this looks fine (although I couldn't sign off even if I wanted to), but do we know for sure if your hunch of the stats being nil if the containers stopped is right?

**Comment by katiewasnothere** [comment]
I see consistent cri crashes from these stats being nil. I've reproed it locally when a container is stopped.

**Review by kevpar — APPROVED** [review]
LGTM

**Comment by dcantah** [comment]
Ok awesome then LGTM also :)

**Pull request merged**
